language: julia
os:
  - linux
julia:
  - 1.4.2
  
script:
- julia -e 'import Pkg; Pkg.build(); Pkg.test(; coverage=true)'

after_success:
 - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'